### ISSUE TITLE
Wrong Json format 

### ISSUE THREAD

**Issue by sergious234** [QuiltMC/update-quilt-meta#20]
So I was writting some code to parse the file `quilt-loader-0.26.0-1.21.json` but the `librariers` object (or whatever is called in json) its wrong (I think) . 

It's suppose to be:

```json
 "libraries": [
    {
      "downloads": {
        "artifact": {
          "path": "ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar",
          "sha1": "1227f9e0666314f9de41477e3ec277e542ed7f7b",
          "size": 1330045,
          "url": "https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar"
        }
      },
      "name": "ca.weblite:java-objc-bridge:1.1",
      "rules": [
        {
          "action": "allow",
          "os": {
            "name": "osx"
          }
        }
      ]
    },
    ... (more downloads)
 ```
source: https://piston-meta.mojang.com/v1/packages/177e49d3233cb6eac42f0495c0a48e719870c2ae/1.21.json

but the quilt json has:

```json
"libraries":  [
		{
			"name": "net.fabricmc:tiny-mappings-parser:0.3.0+build.17",
			"url": "https://maven.fabricmc.net/"
		},
                ... (more objects like the one above)
```
source: The file in my computer

So the right thing to do (I think) it's to put the `url` field inside some `artifact` object which is inside a `downloads` object WHICH IS INSIDE THE LIBRARIES OBJECT/ARRAY AS AN OBJECT. (`name` field as showed before should be outside so no problem with this).

Sorry for my bad English, lots of love Sergio. :)

**Comment by AlexIIL** [comment]
I'm unsure if it's "wrong" necessarily, just not quite the same as what minecraft itself does now. Installing an old version for forge (for example) uses the packed-all-together format.

(And since launchers like MultiMC and the normal minecraft launcher handle it fine, I don't think I agree that it's wrong)

**Comment by sergious234** [comment]
Ok, so if others launchers accepts this format then there is no problem.

Thanks for your response. :)

(I'm closing the issue)
