### ISSUE TITLE
Profile JSON uses Hashed instead of Intermediary

### ISSUE THREAD

**Issue by gdude2002** [QuiltMC/update-quilt-meta#3]
This breaks both ATLauncher and Technic right now

**Comment by Akarys42** [comment]
Is this still an issue?

**Comment by CheaterCodes** [comment]
The profile JSON currently includes both intermediary and hashed. Thanks to an additional fix in loader, this shouldn't be a problem anymore.

**Comment by Akarys42** [comment]
Should this issue be closed then?

**Comment by CheaterCodes** [comment]
Probably
